# Generated by Django 3.0.4 on 2020-03-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobIT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffert',
            name='job_service',
            field=models.CharField(default='JustJoinIT', max_length=128),
        ),
    ]
