# Generated by Django 3.0.4 on 2020-04-02 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobIT', '0002_joboffert_job_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffert',
            options={'verbose_name': 'job offert JJIT'},
        ),
        migrations.AddField(
            model_name='joboffert',
            name='scrappy_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
