# Generated by Django 3.0.4 on 2020-04-09 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobIT', '0003_auto_20200402_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffert',
            name='hash_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=516),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffert',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
