# Generated by Django 3.0.4 on 2020-04-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobIT', '0005_joboffert_still_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffert',
            old_name='url',
            new_name='job_url',
        ),
    ]
