# Generated by Django 3.0.4 on 2020-04-09 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobIT', '0007_joboffert_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffert',
            name='open_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
