# Generated by Django 3.0.4 on 2020-04-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobIT', '0008_joboffert_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffert',
            name='hash_id',
            field=models.CharField(max_length=516, unique=True),
        ),
    ]
