# Generated by Django 3.0.4 on 2020-04-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobIT', '0009_auto_20200420_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffert',
            name='scrapped',
            field=models.BooleanField(default=False),
        ),
    ]
