# Generated by Django 3.0.4 on 2020-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobIT', '0010_joboffert_scrapped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffert',
            name='scrapped',
            field=models.BooleanField(default=True),
        ),
    ]
